"""Domain tool registrations — each submodule registers its @safe_tool functions."""
from tools import (
    utils,
    capacity,
    quotas,
    snapshots,
    synciq,
    nfs,
    s3,
    smb,
    datamover,
    filepool,
    filemgmt,
    users,
    events,
    statistics,
    networking,
    cluster_info,
    jobs,
    performance,
    hardening,
    connectivity,
    quota_reports,
    id_resolution,
    local_info,
)
